
-- TABLE VANPHONG
CREATE TABLE VANPHONG
(
    MAVP CHAR(10) PRIMARY KEY,
    TENVP NVARCHAR(50) NOT NULL
)

-- TABLE NHANVIEN
CREATE TABLE NHANVIEN
(
    MANV CHAR(10) PRIMARY KEY,
    HOTEN NVARCHAR(50) NOT NULL,
    NGAYSINH DATE NOT NULL,
    GIOITINH NCHAR(5) NOT NULL,
    MAVP CHAR(10) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    SODT CHAR(15) NOT NULL,
    FOREIGN KEY (MAVP) REFERENCES VANPHONG(MAVP)
)

-- TABLE THANNHAN
CREATE TABLE THANNHAN
(
    MATN CHAR(10) PRIMARY KEY,
    HOTENTN NVARCHAR(50) NOT NULL,
    NGAYSINH DATE NOT NULL,
    MOILH NVARCHAR(50) NOT NULL,
    MANV CHAR(10) NOT NULL,
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
)

-- INSERT VANPHONG
INSERT INTO VANPHONG
    (MAVP, TENVP)
VALUES
    ('HC', N'Hành Chính'),
    ('CTSV', N'Công tác sinh viên')

-- INSERT NHANVIEN
INSERT INTO NHANVIEN
    (MANV, HOTEN, NGAYSINH, GIOITINH, MAVP, EMAIL, SODT)
VALUES
    ('NV1', N'Nguyễn Anh Tuấn', '1989-11-12', N'Nam', 'HC', 'Tuanna5@fpt.edu.vn', '0988554303'),
    ('NV2', N'Trần Thanh Tùng', '1988-01-02', N'Nam', 'CTSV', 'Tungtt2@fpt.edu.vn', '0987792457'),
    ('NV3', N'Nguyễn Duy Quang Vinh', '2003-11-11', N'Nam', 'HC', 'vinhndqph26105@fpt.edu.vn', '0968739042')

-- INSERT THANNHAN
INSERT INTO THANNHAN
    (MATN, HOTENTN, NGAYSINH, MOILH, MANV)
VALUES
    ('TN01', N'Nguyễn Ngọc Anh', '1962-12-07', N'Người thân', 'NV2'),
    ('TN02', N'Trần Tuấn Tú', '1970-06-06', N'Người quen', 'NV2')

-- CÂU 2: HIỂN THỊ MANV, HOTENNV, MAVP VÀ THÁNG SINH LÀ 8
SELECT
    NV.MANV,
    NV.HOTEN,
    NV.MAVP
FROM NHANVIEN NV
WHERE MONTH(NGAYSINH) = 8

-- CÂU 3: HIỂN THỊ MANV, HOTENNV, MAVP VÀ TUỔI NHÂN VIÊN > 19
SELECT
    NV.MANV,
    NV.HOTEN,
    NV.MAVP,
    DATEDIFF(YEAR, NV.NGAYSINH, GETDATE()) AS 'TUOI_NHAN_VIEN'
FROM NHANVIEN NV
WHERE (DATEDIFF(YEAR, NV.NGAYSINH, GETDATE()) > 19)

-- CÂU 4: HIỂN THỊ THÔNG TIN NHÂN VIÊN HỌ TRẦN
SELECT
    NV.MANV,
    NV.HOTEN,
    VP.TENVP,
    NV.NGAYSINH,
    NV.GIOITINH,
    NV.EMAIL,
    NV.SODT
FROM NHANVIEN NV
    INNER JOIN VANPHONG VP ON VP.MAVP = NV.MAVP
WHERE NV.HOTEN LIKE N'Trần%'

-- CÂU 5: HIỂN THỊ NHÂN VIÊN KHÔNG CÓ THÂN NHÂN
-- CÁCH 1:
SELECT
    NV.*
FROM NHANVIEN NV
    LEFT JOIN THANNHAN TN ON TN.MANV = NV.MANV
WHERE TN.MATN IS NULL

-- CÁCH 2
SELECT
    NV.*
FROM NHANVIEN NV
WHERE NV.MANV NOT IN (
    SELECT TN.MANV
FROM THANNHAN TN
)

-- CÂU 6: THÊM 1 BẢN GHI VÀO BẢNG VANPHONG
INSERT INTO VANPHONG
    (MAVP, TENVP)
VALUES
    ('IT', N'Công Nghệ Thông Tin')

/*
SELECT * FROM VANPHONG
*/

-- CÂU 7: CẬP NHẬT SĐT CỦA NV2
UPDATE NHANVIEN
SET SODT = '0987792444'
WHERE MANV = 'NV2'

/*
SELECT NHANVIEN.*
FROM NHANVIEN
WHERE NHANVIEN.MANV = 'NV2'
*/

-- CÂU 8: XÓA THÔNG TIN THÂN NHÂN CÓ MOILH 'Người quen'
DELETE FROM THANNHAN
WHERE MOILH LIKE N'%Người quen%'
/*
SELECT * FROM THANNHAN
*/