
CREATE DATABASE QUAN_LY_NHAN_VIEN

USE QUAN_LY_NHAN_VIEN

CREATE TABLE PHONG
(
    MA_PHONG INT IDENTITY(1,1) PRIMARY KEY,
    TEN_PHONG NVARCHAR(50) NOT NULL
)

CREATE TABLE NHAN_VIEN
(
    MA_NHAN_VIEN INT IDENTITY(1,1) PRIMARY KEY,
    HO NVARCHAR(10) NOT NULL,
    TEN NVARCHAR(10) NOT NULL,
    NGAY_SINH DATE NOT NULL,
    LUONG INT NOT NULL,
    DIA_CHI NVARCHAR(200) NOT NULL,
    MA_PHONG INT NOT NULL,
    CONSTRAINT KT_LUONG CHECK (LUONG > 0),
    CONSTRAINT FK_NHAN_VIEN_PHONG FOREIGN KEY(MA_PHONG) REFERENCES PHONG(MA_PHONG)
)


INSERT INTO PHONG
    (TEN_PHONG)
VALUES
    (N'Phòng A'),
    (N'Phòng B'),
    (N'Phòng C'),
    (N'Phòng D'),
    (N'Phòng E'),
    (N'Phòng F'),
    (N'Phòng G'),
    (N'Phòng H'),
    (N'Phòng K'),
    (N'Phòng I')

INSERT INTO NHAN_VIEN
    (HO, TEN, NGAY_SINH, LUONG, DIA_CHI, MA_PHONG)
VALUES
    (N'Nguyễn', N'Vinh', '2003-11-11', 100, N'Hà Nội', 3),
    (N'Nguyễn', N'Linh Anh', '2003-11-26', 200, N'HCM', 5),
    (N'Phùng', N'Huyền', '2003-06-17', 500, N'Hà Nội', 1),
    (N'Hoàng', N'Vinh', '1999-02-05', 150, N'Hải Phòng', 9),
    (N'Lưu', N'Quân', '2003-05-29', 300, N'Mê Linh', 7),
    (N'Phan', N'Hùng', '2003-09-04', 700, N'Hà Nội', 2),
    (N'Lưu', N'Đạt', '2000-03-04', 300, N'Phú Thọ', 4),
    (N'Phan', N'Vinh', '1980-12-09', 400, N'Cà Mau', 6),
    (N'Ma', N'Quang Vinh', '1992-10-30', 900, N'Lào Cai', 1),
    (N'Đỗ', N'Việt Anh', '2002-02-13', 100, N'Nghệ An', 2)


SELECT
    NHAN_VIEN.MA_NHAN_VIEN,
    NHAN_VIEN.HO + ' ' + NHAN_VIEN.TEN AS TEN_NHAN_VIEN,
    NHAN_VIEN.LUONG,
    NHAN_VIEN.DIA_CHI,
    PHONG.TEN_PHONG
FROM NHAN_VIEN
    JOIN PHONG ON NHAN_VIEN.MA_PHONG = PHONG.MA_PHONG

SELECT
    HO + ' ' + TEN + N', địa chỉ: ' + DIA_CHI AS 'THONG TIN NHAN VIEN'
FROM NHAN_VIEN



SELECT DISTINCT HO
FROM NHAN_VIEN

SELECT DISTINCT TEN
FROM NHAN_VIEN

SELECT TOP 2
    *
FROM NHAN_VIEN

SELECT TOP 90 PERCENT
    *
FROM NHAN_VIEN

SELECT *
FROM NHAN_VIEN
WHERE LUONG < 300

SELECT *
FROM NHAN_VIEN
WHERE LUONG < 400 AND LUONG > 100

SELECT *
FROM NHAN_VIEN
WHERE (YEAR(NGAY_SINH) >= 2000 AND YEAR(NGAY_SINH) < 2004)

SELECT *
FROM NHAN_VIEN
WHERE (NGAY_SINH >= '2000-01-01' AND NGAY_SINH < '2004-01-01')

SELECT *
FROM NHAN_VIEN
WHERE HO LIKE N'%Nguyễn%'

SELECT *
FROM PHONG
WHERE TEN_PHONG LIKE N'%lap trinh%'

SELECT *
FROM NHAN_VIEN
WHERE (LUONG < 800 AND MA_PHONG = 2)

SELECT MAX(LUONG)
FROM NHAN_VIEN

SELECT MIN(LUONG)
FROM NHAN_VIEN

SELECT AVG(LUONG)
FROM NHAN_VIEN

SELECT COUNT(*)
FROM NHAN_VIEN


-- TÍNH TRUNG BÌNH LƯƠNG CỦA NHÂN VIÊN CÓ NĂM SINH > 2000
SELECT AVG(LUONG) AS 'TRUNG BÌNH LƯƠNG CỦA NHÂN VIÊN CÓ NĂM SINH > 2000'
FROM NHAN_VIEN
WHERE (YEAR(NGAY_SINH) > 2000)


SELECT
    MA_PHONG,
    COUNT(MA_PHONG) AS 'SỐ LƯỢNG NHÂN VIÊN'
FROM NHAN_VIEN
GROUP BY MA_PHONG


-- TÍNH TRUNG BÌNH LƯƠNG NHÂN VIÊN CỦA MỖI PHÒNG
SELECT
    MA_PHONG,
    AVG(LUONG) AS 'TRUNG BÌNH LƯƠNG THEO PHÒNG'
FROM NHAN_VIEN
GROUP BY MA_PHONG


-- HIỂN THỊ LƯƠNG NHÂN VIÊN CAO NHẤT CỦA MỖI PHÒNG
SELECT
    MA_PHONG,
    MAX(LUONG) AS 'LƯƠNG NHÂN VIÊN CAO NHẤT CỦA MỖI PHÒNG'
FROM NHAN_VIEN
GROUP BY MA_PHONG


SELECT
    MA_PHONG,
    MAX(LUONG)
FROM NHAN_VIEN
GROUP BY MA_PHONG
HAVING MAX(LUONG) > 300


-- TÍNH TỔNG LƯƠNG CỦA MỖI NHÂN VIÊN ĐƯỢC NHÓM THEO NHÓM NĂM SINH VÀ TỔNG LƯƠNG > 100
SELECT
    YEAR(NGAY_SINH) AS 'NĂM SINH',
    SUM(LUONG) AS 'TỔNG LƯƠNG'
FROM NHAN_VIEN
GROUP BY YEAR(NGAY_SINH)
HAVING SUM(LUONG) > 100


-- TÍNH TỔNG LƯƠNG CÔNG TY PHẢI TRẢ CHO MỖI PHÒNG BAN, CHỈ NHÓM HÀNG NÀO CÓ CỘT LƯƠNG > 700, CHỈ HIỂN THỊ NHÓM NÀO CÓ TỔNG LƯƠNG > 10000
SELECT
    MA_PHONG,
    SUM(LUONG) AS 'TỔNG LƯƠNG PHẢI TRẢ'
FROM NHAN_VIEN
WHERE LUONG > 700
GROUP BY MA_PHONG
HAVING SUM(LUONG) > 300


-- VIẾT CÂU TRUY VẤN HIỂN THỊ MÃ PHÒNG BAN VÀ LƯƠNG TRUNG BÌNH TƯƠNG ỨNG TỪNG PHÒNG, CHỈ LẤY CÁC HÀNG CÓ MỨC LƯƠNG > 500, CHỈ HIỂN THỊ CÁC PHÒNG CÓ LƯƠNG TRUNG BÌNH > 700 VÀ SẮP XẾP THEO THỨ TỰ GIẢM DẦN THEO CỘT PHÒNG
SELECT
    MA_PHONG,
    AVG(LUONG) AS 'TRUNG BÌNH LƯƠNG'
FROM NHAN_VIEN
WHERE LUONG > 500
GROUP BY MA_PHONG
HAVING AVG(LUONG) > 700
ORDER BY MA_PHONG DESC


SELECT
    NHAN_VIEN.MA_NHAN_VIEN,
    NHAN_VIEN.HO + ' ' + NHAN_VIEN.TEN AS 'HO_TEN',
    NHAN_VIEN.NGAY_SINH,
    NHAN_VIEN.DIA_CHI,
    PHONG.TEN_PHONG
FROM NHAN_VIEN, PHONG
WHERE NHAN_VIEN.MA_PHONG = PHONG.MA_PHONG


-- TÍNH TRUNG BÌNH LƯƠNG CỦA MỖI PHÒNG HIỂN THỊ THEO TÊN PHÒNG
SELECT
    PHONG.TEN_PHONG,
    AVG(NHAN_VIEN.LUONG) AS 'TRUNG BINH LUONG THEO PHONG'
FROM NHAN_VIEN, PHONG
WHERE NHAN_VIEN.MA_PHONG = PHONG.MA_PHONG
GROUP BY PHONG.TEN_PHONG