-- VIẾT CÂU TRUY VẤN LẤY DỮ LIỆU TỪ BẢNG PHÒNG VÀ BẢNG LOẠI PHÒNG HIỂN THỊ CÁC THÔNG TIN SAU:
-- TÊN PHÒNG, TÊN LOẠI PHÒNG, ĐƠN GIÁ
SELECT
    PHONG.TEN_PHONG,
    LOAI_PHONG.TEN_LOAI_PHONG,
    PHONG.GIA_TIEN
FROM PHONG, LOAI_PHONG
WHERE PHONG.MA_LOAI = LOAI_PHONG.MA_LOAI

SELECT
    P.TEN_PHONG,
    LP.TEN_LOAI_PHONG,
    P.GIA_TIEN
FROM PHONG P
    INNER JOIN LOAI_PHONG LP ON LP.MA_LOAI = P.MA_LOAI

-- VIẾT CÂU TRUY VẤN HIỂN THỊ THÔNG TIN ĐẶT PHÒNG NHƯ SAU:
-- TÊN KHÁCH HÀNG, TÊN PHÒNG, NGÀY ĐẶT, SỐ GIỜ THUÊ
SELECT
    KH.TEN,
    P.TEN_PHONG,
    DP.NGAY_DAT,
    DP.SO_GIO_THUE,
    LP.TEN_LOAI_PHONG
FROM KHACH_HANG KH, PHONG P, DAT_PHONG DP, LOAI_PHONG LP
WHERE DP.MA_KH = KH.MA_KT AND DP.MA_PHONG = P.MA_PHONG AND P.MA_LOAI = LP.MA_LOAI


-- VIẾT CÂU TRUY VẤN HIỂN THỊ XEM KHÁCH ĐẶT LOẠI PHÒNG GÌ, TÊN KHÁCH HÀNG, TÊN LOẠI PHÒNG
SELECT
    KHACH_HANG.TEN,
    PHONG.TEN_PHONG,
    LOAI_PHONG.TEN_LOAI_PHONG,
    DAT_PHONG.NGAY_DAT,
    DAT_PHONG.SO_GIO_THUE
FROM KHACH_HANG
    INNER JOIN DAT_PHONG ON DAT_PHONG.MA_KH = KHACH_HANG.MA_KT
    INNER JOIN PHONG ON PHONG.MA_PHONG = DAT_PHONG.MA_PHONG
    INNER JOIN LOAI_PHONG ON PHONG.MA_LOAI = LOAI_PHONG.MA_LOAI



SELECT
    P.TEN_PHONG,
    LP.TEN_LOAI_PHONG
FROM LOAI_PHONG LP
    INNER JOIN PHONG P ON P.MA_LOAI = LP.MA_LOAI


SELECT
    P.TEN_PHONG,
    LP.TEN_LOAI_PHONG
FROM LOAI_PHONG LP
    FULL OUTER JOIN PHONG P ON P.MA_LOAI = LP.MA_LOAI


SELECT
    P.TEN_PHONG,
    LP.TEN_LOAI_PHONG
FROM LOAI_PHONG LP
    LEFT JOIN PHONG P ON P.MA_LOAI = LP.MA_LOAI


-- HIỂN THỊ THÔNG TIN PHÒNG CÓ GIÁ TIỀN LỚN HƠN GIÁ TIỀN TRUNG BÌNH CỦA CÁC PHÒNG
SELECT *
FROM PHONG
WHERE GIA_TIEN > (SELECT AVG(GIA_TIEN)
FROM PHONG)

-- HIỂN THỊ TÊN PHÒNG CÓ GIÁ TIỀN LỚN NHẤT
SELECT
    PHONG.TEN_PHONG
FROM PHONG
WHERE GIA_TIEN >= (SELECT MAX(GIA_TIEN)
FROM PHONG)

-- HIỂN THỊ TÊN KHÁCH HÀNG CÓ THÁNG SINH NHỎ NHẤT
SELECT
    KHACH_HANG.TEN
FROM KHACH_HANG
WHERE MONTH(NGAY_SINH) <=
(SELECT MIN(MONTH(NGAY_SINH))
FROM KHACH_HANG)


/* CÂU LỆNH THAO TÁC DỮ LIỆU */
-- 1. THÊM DỮ LIỆU
INSERT INTO LOAI_PHONG
    (TEN_LOAI_PHONG)
VALUES
    (N'Phong sieu cap vip pro')

INSERT INTO PHONG
    (TEN_PHONG, GIA_TIEN, MA_LOAI)
VALUES
    (N'P709', 123456, 3),
    (N'P710', 120000, 2),
    (N'P711', 150000, 3)


-- THÊM 3 DỮ LIỆU VÀO BẢNG KHÁCH HÀNG
INSERT INTO KHACH_HANG
    (HO, TEN, DIA_CHI, SDT, NGAY_SINH)
VALUES
    (N'Nguyễn', N'Vinh', N'Hà Nội', '0123456789', '2003-11-11'),
    (N'Nguyễn', N'Long', N'HCM', '0987654321', '1997-03-22'),
    (N'Mạnh', N'Tuấn', N'Hà Nội', '012345678', '2000-01-26')

UPDATE PHONG
SET GIA_TIEN = 13000, TEN_PHONG = 'P712'
WHERE MA_PHONG = 6

-- CẬP NHẬT THÊM 10% GIÁ TIỀN CHO CÁC PHÒNG THUỘC LOẠI PHÒNG LÀ VIP
UPDATE PHONG
SET GIA_TIEN += GIA_TIEN * 0.1
WHERE MA_LOAI = (SELECT MA_LOAI
FROM LOAI_PHONG
WHERE TEN_LOAI_PHONG LIKE '%vip%')

-- CÂU LỆNH XÓA
DELETE FROM LOAI_PHONG
WHERE MA_LOAI = 4