
CREATE DATABASE FINAL_TEST_COM2012
USE FINAL_TEST_COM2012


CREATE TABLE KHACHHANG
(
    MAKH CHAR(10) PRIMARY KEY NOT NULL,
    TENKH NVARCHAR(50) NOT NULL,
    TAIKHOAN CHAR(10) NOT NULL
)

CREATE TABLE SACH
(
    MAS CHAR(10) PRIMARY KEY NOT NULL,
    TIEUDE NVARCHAR(50) NOT NULL,
    DONGIA INT NOT NULL,
    GHICHU NVARCHAR(100) NOT NULL
)

CREATE TABLE DONHANG
(
    MADH CHAR(10) PRIMARY KEY NOT NULL,
    MAKH CHAR(10) NOT NULL,
    MAS CHAR(10) NOT NULL,
    SOLUONG INT NOT NULL,
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY (MAS) REFERENCES SACH(MAS)
)


-- CÂU 2: HIỂN THỊ THÔNG TIN: MAKH, TENKH, MAS, SOLUONG, DONGIA, THANHTIEN (1đ)
SELECT
    KHACHHANG.MAKH,
    KHACHHANG.TENKH,
    SACH.MAS,
    DONHANG.SOLUONG,
    SACH.DONGIA,
    DONHANG.SOLUONG * SACH.DONGIA AS 'THANH_TIEN'
FROM KHACHHANG
    INNER JOIN DONHANG ON DONHANG.MAKH = KHACHHANG.MAKH
    INNER JOIN SACH ON SACH.MAS = DONHANG.MAS

-- CÂU 3: HIỂN THỊ TOP 2 KHÁCH HÀNG MUA HÀNG VỚI SỐ TIỀN NHIỀU NHẤT GỒM CÁC THÔNG TIN SAU: MAKH, MAS, SOLUONG, DONGIA, THANHTIEN (1đ)
SELECT TOP 2
    KHACHHANG.MAKH,
    SACH.MAS,
    DONHANG.SOLUONG,
    SACH.DONGIA,
    DONHANG.SOLUONG * SACH.DONGIA AS 'THANH_TIEN'
FROM KHACHHANG
    INNER JOIN DONHANG ON DONHANG.MAKH = KHACHHANG.MAKH
    INNER JOIN SACH ON SACH.MAS = DONHANG.MAS
ORDER BY DONHANG.SOLUONG * SACH.DONGIA DESC

-- CÂU 4: HIỂN THỊ CÁC SÁCH CÓ SỐ LƯỢNG NẰM TRONG KHOẢNG TỪ 10 ĐẾN 20 (1đ)
SELECT
    *
FROM SACH
WHERE MAS IN (SELECT MAS
FROM DONHANG
GROUP BY MAS
HAVING SUM(SOLUONG) BETWEEN 10 AND 20)

-- CÂU 5: HIỂN THỊ MADH, MAKH, TỔNGTHÀNHTIỀN ĐÃ MUA TRONG TỪNG ĐƠN HÀNG. CHỈ HIỂN THỊ NHỮNG ĐƠN HÀNG CÓ TỔNG THÀNH TIỀN >= 500.000 VÀ SẮP XẾP THEO THỨ TỰ GIẢM DẦN CỦA CỘT TỔNG THÀNH TIỀN (1đ)
SELECT
    DONHANG.MADH,
    DONHANG.MAKH,
    DONHANG.SOLUONG * SACH.DONGIA AS TONG_THANH_TIEN
FROM DONHANG
    INNER JOIN SACH ON SACH.MAS = DONHANG.MAS
WHERE DONHANG.SOLUONG * SACH.DONGIA >= 500000
ORDER BY DONHANG.SOLUONG * SACH.DONGIA DESC

-- CÂU 6: HIỂN THỊ TÊN SÁCH CÓ SỐ LƯỢNG ĐẶT MUA NHỎ HƠN SỐ LƯỢNG MUA TRUNG BÌNH CỦA CÁC SÁCH (1đ)
SELECT SACH.TIEUDE
FROM SACH
WHERE
SACH.MAS IN (SELECT DONHANG.MAS
FROM DONHANG
GROUP BY DONHANG.MAS
HAVING SUM(DONHANG.SOLUONG) < (SELECT AVG(DONHANG.SOLUONG)
FROM DONHANG)
)

-- CÂU 7: CHÈN THÊM MỘT BẢN GHI MỚI VÀO BẢNG SACH (1đ)
INSERT INTO SACH
    (MAS, TIEUDE,DONGIA,GHICHU)
VALUES('S04', N'Cơ sở dữ liệu', 261100, N'Mới nhập')

-- CÂU 8: CẬP NHẬT LẠI SỐ TAIKHOAN CỦA KHÁCH HÀNG KH3 LÀ : '00000001' (1đ)
UPDATE KHACHHANG
SET TAIKHOAN = '00000001'
WHERE MAKH = 'KH3'